### PR TITLE
Feat: separate out example app into its own module

### PR DESCRIPTION
**Pull request by ctlong**
This example app should not share the same go.mod as the production
code. It should be maintained separately.

Since we probably won't import that app anywhere, it's module name
doesn't matter, so I named it `example`.

Had to bump the version of github.com/cactus/go-statsd-client imported
to v5 because it was so old that no version had been released yet, and
there was no statsd package to import.

### CODE REVIEW

**Comment by ctlong** [comment]
Also resolves all of the remaining `golangci-lint` warnings :).

**Comment by Benjamintf1** [comment]
`This example app should not share the same go.mod as the production
code. It should be maintained separately.`

Not sure why we necessarily want this, but lgtm otherwise. (do we not pull in this path into our bosh release?)

**Review by Benjamintf1 — APPROVED** [review]
-

**Comment by ctlong** [comment]
We don't pull this path into our bosh release, or any bosh release as far as I can tell.

That whole tools directory seems like example testing code, which we could also just pull out if we don't want to keep it around / maintain it. Maybe it's a relic from some old CI?

**Comment by Benjamintf1** [comment]
@ctlong https://github.com/cloudfoundry/statsd-injector-release/blob/f1342e48171dbccd6a8848bc6b7d0fdaf232aa64/packages/statsd_injector/spec#L7

**Comment by Benjamintf1** [comment]
might be old ci stuff. If it's not even deployed in ci, we could just get rid of it?

**Comment by ctlong** [comment]
> https://github.com/cloudfoundry/statsd-injector-release/blob/f1342e48171dbccd6a8848bc6b7d0fdaf232aa64/packages/statsd_injector/spec#L7

Hmmm good callout. Yet the packaging script doesn't build it

https://github.com/cloudfoundry/statsd-injector-release/blob/f1342e48171dbccd6a8848bc6b7d0fdaf232aa64/packages/statsd_injector/packaging#L1-L6

And nothing within the code references it as far as I can tell.

I'm in favor of getting rid of it + the other two examples.

**Pull request merged**
